/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { SalesReport } from "./SalesReport";
import { SalesReportCountArgs } from "./SalesReportCountArgs";
import { SalesReportFindManyArgs } from "./SalesReportFindManyArgs";
import { SalesReportFindUniqueArgs } from "./SalesReportFindUniqueArgs";
import { CreateSalesReportArgs } from "./CreateSalesReportArgs";
import { UpdateSalesReportArgs } from "./UpdateSalesReportArgs";
import { DeleteSalesReportArgs } from "./DeleteSalesReportArgs";
import { Employee } from "../../employee/base/Employee";
import { SalesReportService } from "../salesReport.service";
@graphql.Resolver(() => SalesReport)
export class SalesReportResolverBase {
  constructor(protected readonly service: SalesReportService) {}

  async _salesReportsMeta(
    @graphql.Args() args: SalesReportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SalesReport])
  async salesReports(
    @graphql.Args() args: SalesReportFindManyArgs
  ): Promise<SalesReport[]> {
    return this.service.salesReports(args);
  }

  @graphql.Query(() => SalesReport, { nullable: true })
  async salesReport(
    @graphql.Args() args: SalesReportFindUniqueArgs
  ): Promise<SalesReport | null> {
    const result = await this.service.salesReport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SalesReport)
  async createSalesReport(
    @graphql.Args() args: CreateSalesReportArgs
  ): Promise<SalesReport> {
    return await this.service.createSalesReport({
      ...args,
      data: {
        ...args.data,

        employee: args.data.employee
          ? {
              connect: args.data.employee,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SalesReport)
  async updateSalesReport(
    @graphql.Args() args: UpdateSalesReportArgs
  ): Promise<SalesReport | null> {
    try {
      return await this.service.updateSalesReport({
        ...args,
        data: {
          ...args.data,

          employee: args.data.employee
            ? {
                connect: args.data.employee,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SalesReport)
  async deleteSalesReport(
    @graphql.Args() args: DeleteSalesReportArgs
  ): Promise<SalesReport | null> {
    try {
      return await this.service.deleteSalesReport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SalesReport)
  async uploadFile(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: SalesReportFindUniqueArgs
  ): Promise<SalesReport> {
    return await this.service.uploadFile(args, file);
  }

  @graphql.Mutation(() => SalesReport)
  async deleteFile(
    @graphql.Args()
    args: SalesReportFindUniqueArgs
  ): Promise<SalesReport> {
    return await this.service.deleteFile(args);
  }

  @graphql.ResolveField(() => Employee, {
    nullable: true,
    name: "employee",
  })
  async getEmployee(
    @graphql.Parent() parent: SalesReport
  ): Promise<Employee | null> {
    const result = await this.service.getEmployee(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
